steps:
  # ==============================================================================
  # STEP 1: Build the Container Image
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '.'

  # ==============================================================================
  # STEP 2: Push the Container Image to Artifact Registry
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image (Commit SHA)'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image (Latest)'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'

  # ==============================================================================
  # STEP 3: Deploy to Cloud Run
  # ==============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--timeout=600'
      # Ensure database and LLM environment variables match the target environment
      - '--update-env-vars'
      - 'POSTGRES_DATABASE=${_DB_NAME}'
      - '--update-env-vars'
      - 'LLM_BINDING=openai'
      - '--update-env-vars'
      - 'EMBEDDING_BINDING=openai'
      - '--update-env-vars'
      - 'LLM_MODEL=gpt-4.1-mini'
      - '--update-env-vars'
      - 'EMBEDDING_MODEL=text-embedding-3-large'
      - '--update-env-vars'
      - 'EMBEDDING_DIM=3072'
      # Remove conflicting literal environment variables before mounting secrets
      - '--remove-env-vars=POSTGRES_PASSWORD,LLM_BINDING_API_KEY,EMBEDDING_BINDING_API_KEY'
      # Mount secrets for multi-tenancy and database access
      # IMPORTANT: Do NOT mount secrets under /app directly.
      # Cloud Run mounts secrets as volumes; mounting at /app can hide the application code (/app/lightrag).
      # Instead mount to a dedicated path and point the app at it via USERS_JSON_PATH.
      - '--update-env-vars'
      - 'USERS_JSON_PATH=/var/secrets/lightrag/users.json'
      - '--set-secrets=/var/secrets/lightrag/users.json=lightrag-users-config:latest,POSTGRES_PASSWORD=${_DB_SECRET_NAME}:latest,LLM_BINDING_API_KEY=lightrag-openai-api-key:latest,EMBEDDING_BINDING_API_KEY=lightrag-openai-api-key:latest'

# ==============================================================================
# SUBSTITUTIONS
# These variables can be overridden in the Cloud Build Trigger configuration
# ==============================================================================
substitutions:
  _REGION: northamerica-northeast2
  _REPO_NAME: cloud-run-source-deploy
  _IMAGE_NAME: lightrag/lightrag
  # Default values (Targeting Staging by default for safety)
  _SERVICE_NAME: lightrag-staging
  _DB_NAME: lightrag_staging
  _DB_SECRET_NAME: lightrag-staging-postgres-password

# ==============================================================================
# IMAGES
# ==============================================================================
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
