steps:
  # ==============================================================================
  # STEP 1: Build the Container Image
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '.'

  # ==============================================================================
  # STEP 2: Push the Container Image to Artifact Registry
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image (Commit SHA)'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image (Latest)'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'

  # ==============================================================================
  # STEP 3: Deploy to Cloud Run
  # ==============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--timeout=600'
      # Ensure database environment variable matches the target environment
      - '--update-env-vars'
      - 'POSTGRES_DATABASE=${_DB_NAME}'
      # Remove conflicting literal environment variables before mounting secrets
      - '--remove-env-vars=POSTGRES_PASSWORD,LLM_BINDING_API_KEY,EMBEDDING_BINDING_API_KEY'
      # Mount secrets for multi-tenancy and database access
      - '--set-secrets=/app/users.json=lightrag-users-config:latest,POSTGRES_PASSWORD=lightrag-postgres-password:latest,LLM_BINDING_API_KEY=lightrag-openai-api-key:latest,EMBEDDING_BINDING_API_KEY=lightrag-openai-api-key:latest'

# ==============================================================================
# SUBSTITUTIONS
# These variables can be overridden in the Cloud Build Trigger configuration
# ==============================================================================
substitutions:
  _REGION: northamerica-northeast2
  _REPO_NAME: cloud-run-source-deploy
  _IMAGE_NAME: lightrag/lightrag
  # Default values (Targeting Staging by default for safety)
  _SERVICE_NAME: lightrag-staging
  _DB_NAME: lightrag_staging

# ==============================================================================
# IMAGES
# ==============================================================================
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
